server:
  ip: localhost
  port: 2025
  max-http-header-size: 2MB

spring:
  servlet:  # 新增 Multipart 配置
    multipart:
      enabled: true        # 必须显式启用
      max-file-size: 100MB # 单个文件大小限制
      max-request-size: 100MB # 整个请求大小限制
      location: ${java.io.tmpdir} # 临时存储目录（可选）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/sql?serverTimezone=GMT%2b8
    url: jdbc:mysql://121.250.208.122:3306/sql?serverTimezone=GMT%2b8
    username: root
    password: 896896
  mail:
    host: smtp.qq.com
    port: 465
    username: 896826234@qq.com
    password: mayiozbgxfzlbega
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          connectiontimeout: 5000
          timeout: 5000

mybatis:
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

deepseek:
  api:
    key: sk-a0bc3d1bb1cd4a88aceb5a7bbcea243a
    url: https://api.deepseek.com/v1/chat/completions
